<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <RootNamespace>GtMotive.Estimate.Microservice.DevTokenGenerator</RootNamespace>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <NoWarn>1591;CA1515</NoWarn>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\GtMotive.Estimate.Microservice.Infrastructure\GtMotive.Estimate.Microservice.Infrastructure.csproj" />
    </ItemGroup>

</Project>
